server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: notification-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.payments.notification.event.PaymentAuthorizedEvent
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0 # Rastreia 100% das requisições
  otlp:
    tracing:
      # Endpoint HTTP OTLP do Grafana Tempo ou Jaeger
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
app:
  kafka:
    topics:
      transacao-autorizada: transacao-autorizada

logging:
  level:
    root: INFO
    com.payments.notification: DEBUG
    org.springframework.web: INFO
