apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      # Permite navegar dos spans do trace de volta para os logs no Loki
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-2m'
        spanEndTimeShift: '2m'
        filterByTraceId: true
        filterBySpanId: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      httpMethod: GET
      derivedFields:
        - name: "Message log TraceID"
          datasourceUid: tempo
          matcherRegex: "(?:trace_id=|traceId=|\"traceId\":\\s*\")([a-f0-9]{32})"
          url: '$${__value.raw}'
        - name: "Label log TraceID"
          datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          url: '$${__value.raw}'

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
