server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authorization-payments-route
          uri: ${AUTHORIZATION_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/payments, /api/v1/payments/**
        - id: antifraud-evaluations-route
          uri: ${ANTIFRAUD_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/antifraud, /api/v1/antifraud/**
        - id: authorization-service
          uri: ${AUTHORIZATION_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/authorization-service/v3/api/docs
        - id: antifraud-service
          uri: ${ANTIFRAUD_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/antifraud-service/v3/api/docs
        - id: ledger-accounts-route
          uri: ${LEDGER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/accounts, /api/v1/accounts/**
        - id: ledger-service
          uri: ${LEDGER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/ledger-service/v3/api/docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0 # Rastreia 100% das requisições
  otlp:
    logging:
      endpoint: ${MANAGEMENT_OTLP_LOGGING_ENDPOINT:http://localhost:4318/v1/logs}
    tracing:
      # Endpoint HTTP OTLP do Grafana Tempo ou Jaeger
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: authorization-service
        url: /authorization-service/v3/api/docs
      - name: antifraud-service
        url: /antifraud-service/v3/api/docs
      - name: ledger-service
        url: /ledger-service/v3/api/docs

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
