/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * Authorization System
 * Service version: 1.0.0
 */
import { URL } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

/**
 * Método de pagamento a ser utilizado
 */
export type PaymentAuthorizationRequestDtoPaymentMethod =
  (typeof PaymentAuthorizationRequestDtoPaymentMethod)[keyof typeof PaymentAuthorizationRequestDtoPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentAuthorizationRequestDtoPaymentMethod = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  PIX: "PIX",
} as const;

/**
 * Dados para solicitação de autorização de pagamento
 */
export interface PaymentAuthorizationRequestDto {
  /** Identificador único da conta de origem */
  accountId: string;
  /** Identificador único do estabelecimento comercial */
  merchantId: string;
  /** Valor monetário a ser debitado/autorizado */
  amount: number;
  /** Código ISO 4217 da moeda */
  currency: string;
  /** Método de pagamento a ser utilizado */
  paymentMethod: PaymentAuthorizationRequestDtoPaymentMethod;
  /** Token seguro representativo dos dados do cartão */
  cardToken: string;
}

export type ProblemDetailProperties = {
  [key: string]: { [key: string]: unknown };
};

export interface ProblemDetail {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  properties?: ProblemDetailProperties;
}

/**
 * Status final da autorização
 */
export type PaymentAuthorizationResponseDtoStatus =
  (typeof PaymentAuthorizationResponseDtoStatus)[keyof typeof PaymentAuthorizationResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentAuthorizationResponseDtoStatus = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

/**
 * Resultado da solicitação de autorização de pagamento
 */
export interface PaymentAuthorizationResponseDto {
  /** Identificador único do pagamento gerado */
  paymentId?: string;
  /** Status final da autorização */
  status?: PaymentAuthorizationResponseDtoStatus;
  /** Código de autorização gerado em caso de aprovação */
  authorizationCode?: string;
  /** Valor autorizado */
  amount?: number;
  /** Moeda da transação */
  currency?: string;
  /** Data e hora de criação da transação */
  createdAt?: string;
}

export type AuthorizePaymentHeaders = {
  /**
   * Chave única de idempotência no formato UUID para evitar duplicações de cobrança
   */
  "Idempotency-Key": string;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class AuthorizationSystemClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  /**
   * Submete uma transação financeira para autorização com garantia estrita de idempotência e análise antifraude.
   * @summary Autorizar pagamento
   */
  authorizePayment(
    paymentAuthorizationRequestDto: PaymentAuthorizationRequestDto,
    headers: AuthorizePaymentHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PaymentAuthorizationResponseDto | PaymentAuthorizationResponseDto;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/payments`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(paymentAuthorizationRequestDto),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "authorizePayment",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
