{
 "title": "MICROSERVICES METRICS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Throughput por Microsserviço",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, uri) (rate(http_server_requests_seconds_count{uri!=\"UNKNOWN\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{job}} throughput"
    }
   ]
  },
  {
   "title": "HTTP STATUS 4xx | 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!=\"UNKNOWN\", uri!=\"/actuator/prometheus\", status=~\"[45]..\"}[1m])) by (uri, status, method)",
     "legendFormat": "{{method}}  {{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Outbox Failed Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outbox_failed_events", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Outbox Pending Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outbox_pending_events", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Outbox Sent Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outbox_sent_events", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "⏱️ Duration (Latência p50, p95 e p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket[1m])) by (le, job,uri))",
     "legendFormat": "{{job}} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le, job,uri))",
     "legendFormat": "{{job}} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "{{job}} - p99"
    }
   ]
  },
  {
   "title": "Pagamentos Processados por método",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job, payment_method, status) (payments_authorized_count_total{job=\"authorization-service\"})",
     "legendFormat": "{{payment_method}}"
    }
   ]
  },
  { "title": "Payment Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "New Panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{service_name=\"authorization-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "filters": [
      { "id": "ac17511b", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "gateway-service" ],
       "valueType": "string"
      },
      { "id": "duration-type", "value": "span" },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": "http get /actuator/prometheus",
       "valueType": "string"
      }
     ],
     "limit": 2000,
     "tableType": "traces"
    }
   ]
  }
 ]
}