server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: antifraud-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /antifraud-service/v3/api/docs
  override-server-url: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO
    com.payments.antifraud: DEBUG
