server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: antifraud-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0 # Rastreia 100% das requisições
  otlp:
    logging:
      endpoint: ${MANAGEMENT_OTLP_LOGGING_ENDPOINT:http://localhost:4318/v1/logs}
    tracing:
      # Endpoint HTTP OTLP do Grafana Tempo ou Jaeger
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

springdoc:
  api-docs:
    path: /antifraud-service/v3/api/docs
  override-server-url: true

logging:
  level:
    root: INFO
    com.payments.antifraud: DEBUG
