apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    deriveFieldsFromLogs: true
    jsonData:
      derivedFields:
        - datasourceName: Tempo
          datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id=(\w+)
          name: traceID
          url: '$${__value.raw}'