receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 256

exporters:
  debug:
    verbosity: detailed
  otlp_http/loki:
    endpoint: http://loki:3100/otlp
  otlp_grpc/tempo:                    # <- coloca aqui o exporter que você já usava pro Tempo
    endpoint: http://tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:                      # <- pipeline que sumiu
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/loki, debug]